daemon off;
error_log stderr;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    server {
        listen 8080;
        root /usr/share/nginx/html;
        index index.html;
        
        # Servir archivos estáticos
        location / {
            try_files $uri $uri/ /index.html;
            add_header Cache-Control "no-cache";
        }

        # Servir el index.html para rutas de React Router
        location ~ \.html$ {
            add_header Cache-Control "no-cache";
        }

        # Servir archivos estáticos con cache
        location /static/ {
            expires 1y;
            add_header Cache-Control "public";
        }

        # Manejar errores 404
        error_page 404 /index.html;
    }
}
