[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
buildContext = "."

[deploy]
startCommand = "/start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.variables]]
key = "PORT"
value = "80"

[[deploy.variables]]
key = "DJANGO_SETTINGS_MODULE"
value = "almacen.settings"
