[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
healthcheckPath = "/admin/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.variables]]
key = "PYTHONPATH"
value = "/app"

[[deploy.variables]]
key = "DJANGO_SETTINGS_MODULE"
value = "almacen.settings"

[[deploy.variables]]
key = "DEBUG"
value = "False"

[[deploy.variables]]
key = "ALLOWED_HOSTS"
value = ".railway.app"
