services:
  - type: web
    name: under-gestion-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: DATABASE_URL
        fromDatabase:
          name: under-gestion-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: under-gestion-api.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://under-gestion-frontend.onrender.com
    healthCheckPath: /api/health/
    autoDeploy: true

databases:
  - name: under-gestion-db
    databaseName: under_gestion
    user: under_gestion
    plan: free
