# Generated by Django 5.1.3 on 2024-11-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_estado_historialproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Cocina', 'Cocina'), ('Almacen', 'Almacén'), ('EPPS', 'EPPS')], default='Cocina', max_length=50),
        ),
    ]
