# Generated by Django 5.1.3 on 2024-11-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_salidaproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
