# Generated by Django 5.1.3 on 2024-11-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_producto_estado_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='No disponible', editable=False, max_length=50),
        ),
    ]
