# Generated by Django 5.1.3 on 2024-11-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('Unidad', 'Unidad'), ('Kg', 'Kg'), ('Par', 'Par'), ('Lt', 'Lt')], default='Unidad', max_length=50),
        ),
    ]
