# Generated by Django 5.1.3 on 2024-12-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_remove_noticia_imagen_imagennoticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
