# Generated by Django 5.1.3 on 2024-12-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_perfilusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'permissions': [('full_access', 'Acceso total al sistema')]},
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='es_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='puede_editar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='puede_eliminar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='puede_escribir',
            field=models.BooleanField(default=True),
        ),
    ]
