# Generated by Django 5.1.4 on 2024-12-26 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('procedencia', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Cuenta')),
                ('numero_cci', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de CCI')),
                ('banco', models.CharField(blank=True, choices=[('BCP', 'Banco de Crédito del Perú'), ('BBVA', 'BBVA'), ('Interbank', 'Interbank'), ('Scotiabank', 'Scotiabank'), ('BN', 'Banco de la Nación'), ('Otros', 'Otros')], max_length=20, null=True, verbose_name='Entidad Bancaria')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('OPERADOR', 'Operador')], default='OPERADOR', max_length=20)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Tareo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('UNIDAD', 'En Unidad'), ('PERMISO', 'Permiso'), ('FALTA', 'Falta'), ('DESCANSO', 'Descanso Médico'), ('DIAS_LIBRES', 'Días Libres'), ('OTROS', 'Otros')], default='UNIDAD', max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareos', to='personales.personal')),
            ],
            options={
                'ordering': ['-fecha', 'personal__apellidos'],
                'unique_together': {('personal', 'fecha')},
            },
        ),
    ]
