# Generated by Django 5.1.4 on 2024-12-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personales', '0002_alter_personal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.AddField(
            model_name='personal',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='procedencia',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
