# Generated by Django 5.1.4 on 2024-12-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personales', '0003_alter_personal_options_personal_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['apellidos', 'nombres']},
        ),
        migrations.AlterField(
            model_name='personal',
            name='procedencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
