# Generated by Django 5.1.4 on 2024-12-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personales', '0004_alter_personal_options_alter_personal_procedencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='banco',
            field=models.CharField(blank=True, choices=[('BCP', 'Banco de Crédito del Perú'), ('BBVA', 'BBVA'), ('Interbank', 'Interbank'), ('Scotiabank', 'Scotiabank'), ('BN', 'Banco de la Nación'), ('Otros', 'Otros')], max_length=20, null=True, verbose_name='Entidad Bancaria'),
        ),
        migrations.AddField(
            model_name='personal',
            name='numero_cci',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de CCI'),
        ),
        migrations.AddField(
            model_name='personal',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Cuenta'),
        ),
    ]
