# Generated by Django 5.1.4 on 2024-12-26 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personales', '0004_alter_personal_options_alter_personal_procedencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='banco',
            field=models.CharField(blank=True, choices=[('BCP', 'Banco de Crédito del Perú'), ('BBVA', 'BBVA'), ('Interbank', 'Interbank'), ('Scotiabank', 'Scotiabank'), ('BN', 'Banco de la Nación'), ('Otros', 'Otros')], max_length=20, null=True, verbose_name='Entidad Bancaria'),
        ),
        migrations.AddField(
            model_name='personal',
            name='numero_cci',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de CCI'),
        ),
        migrations.AddField(
            model_name='personal',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Cuenta'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('OPERADOR', 'Operador')], default='OPERADOR', max_length=20)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Tareo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('UNIDAD', 'En Unidad'), ('PERMISO', 'Permiso'), ('FALTA', 'Falta'), ('DESCANSO', 'Descanso Médico'), ('DIAS_LIBRES', 'Días Libres'), ('OTROS', 'Otros')], default='UNIDAD', max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareos', to='personales.personal')),
            ],
            options={
                'ordering': ['-fecha', 'personal__apellidos'],
                'unique_together': {('personal', 'fecha')},
            },
        ),
    ]
