# Generated by Django 5.1.4 on 2025-02-06 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personales', '0004_update_tipo_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareo',
            options={'ordering': ['fecha', 'personal']},
        ),
        migrations.RenameField(
            model_name='tareo',
            old_name='motivo',
            new_name='observaciones',
        ),
        migrations.AddField(
            model_name='tareo',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tareo',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personales.personal'),
        ),
        migrations.AlterField(
            model_name='tareo',
            name='tipo',
            field=models.CharField(choices=[('T', 'En Unidad'), ('PS', 'Permiso Sin Goce'), ('PC', 'Permiso Con Goce'), ('DL', 'Días Libres'), ('DM', 'Descanso Médico'), ('TL', 'Trabaja en Lima'), ('F', 'Falta'), ('R', 'Renuncia')], max_length=2),
        ),
    ]
