# Generated by Django 5.1.4 on 2024-12-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personales', '0005_personal_banco_personal_numero_cci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
