# Generated by Django 5.1.4 on 2024-12-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personales', '0006_alter_personal_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTareo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PERMISO', 'Permiso'), ('DIA_LIBRE', 'Día Libre'), ('UNIDAD', 'En Unidad'), ('RENUNCIA', 'Renuncia'), ('FALTA', 'Falta'), ('DESCANSO_MEDICO', 'Descanso Médico')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tareo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos_tareo/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('unidad_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareos', to='personales.personal')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personales.tipotareo')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
