# Generated by Django 5.1.4 on 2024-12-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personales', '0007_tipotareo_tareo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareo',
            name='tipo',
            field=models.CharField(choices=[('UNIDAD', 'En Unidad'), ('PERMISO', 'Permiso'), ('FALTA', 'Falta'), ('DESCANSO', 'Descanso Médico'), ('VACACIONES', 'Vacaciones'), ('OTROS', 'Otros')], default='UNIDAD', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='tareo',
            options={'ordering': ['-fecha', 'personal__apellidos']},
        ),
        migrations.RenameField(
            model_name='tareo',
            old_name='fecha_inicio',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='tareo',
            old_name='observaciones',
            new_name='motivo',
        ),
        migrations.AlterUniqueTogether(
            name='tareo',
            unique_together={('personal', 'fecha')},
        ),
        migrations.DeleteModel(
            name='TipoTareo',
        ),
        migrations.RemoveField(
            model_name='tareo',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='tareo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tareo',
            name='fecha_fin',
        ),
    ]
