# Generated by Django 5.1.4 on 2024-12-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personales', '0008_alter_tareo_tipo_alter_tareo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareo',
            name='unidad_trabajo',
        ),
        migrations.AlterField(
            model_name='tareo',
            name='tipo',
            field=models.CharField(choices=[('UNIDAD', 'En Unidad'), ('PERMISO', 'Permiso'), ('FALTA', 'Falta'), ('DESCANSO', 'Descanso Médico'), ('DIA_LIBRE', 'Día Libre'), ('OTROS', 'Otros')], default='UNIDAD', max_length=20),
        ),
    ]
