# Generated by Django 5.1.4 on 2024-12-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personales', '0009_remove_tareo_unidad_trabajo_alter_tareo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareo',
            name='tipo',
            field=models.CharField(choices=[('UNIDAD', 'En Unidad'), ('PERMISO', 'Permiso'), ('FALTA', 'Falta'), ('DESCANSO', 'Descanso Médico'), ('DIAS_LIBRES', 'Días Libres (Vacaciones)'), ('OTROS', 'Otros')], default='UNIDAD', max_length=20),
        ),
    ]
