# Generated by Django 5.1.4 on 2025-02-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('armadas', models.IntegerField()),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Longitud (pies)')),
                ('turno', models.CharField(choices=[('DIA', 'Día'), ('NOCHE', 'Noche')], default='DIA', max_length=10)),
                ('perforacion', models.CharField(choices=[('EXTRACCION', 'Extracción'), ('AVANCE', 'Avance')], default='EXTRACCION', max_length=10)),
            ],
            options={
                'verbose_name': 'Registro de Voladura',
                'verbose_name_plural': 'Registros de Voladura',
                'ordering': ['-fecha'],
            },
        ),
    ]
