# Generated by Django 5.1.4 on 2025-02-11 03:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blasting', '0002_alter_blasting_options_alter_blasting_armadas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blasting',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Blasting', 'verbose_name_plural': 'Blasting'},
        ),
        migrations.AddField(
            model_name='blasting',
            name='emulnor',
            field=models.IntegerField(default=0, help_text='Cantidad de emulnor utilizado', verbose_name='Emulnor'),
        ),
        migrations.AddField(
            model_name='blasting',
            name='fulminantes',
            field=models.IntegerField(default=0, help_text='Número de fulminantes utilizados', verbose_name='Fulminantes'),
        ),
        migrations.AddField(
            model_name='blasting',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blasting',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
