# Generated by Django 5.1.4 on 2025-02-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blasting', '0003_alter_blasting_options_blasting_emulnor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blasting',
            options={'ordering': ['-fecha'], 'verbose_name': 'Blasting', 'verbose_name_plural': 'Blasting'},
        ),
        migrations.RemoveField(
            model_name='blasting',
            name='emulnor',
        ),
        migrations.RemoveField(
            model_name='blasting',
            name='fulminantes',
        ),
        migrations.RemoveField(
            model_name='blasting',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='blasting',
            name='usuario',
        ),
    ]
