# Generated by Django 5.1.4 on 2025-02-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='historialproducto',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
        migrations.DeleteModel(
            name='HistorialProducto',
        ),
    ]
