# Generated by Django 5.1.4 on 2025-02-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_historialproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(db_index=True),
        ),
    ]
