# Generated by Django 5.1.3 on 2024-12-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0026_alter_historialproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialproducto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
