# Generated by Django 5.1.4 on 2024-12-24 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personales', '0004_alter_personal_options_alter_personal_procedencia_and_more'),
        ('productos', '0028_alter_historialproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaproducto',
            name='entregado_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_recibidas', to='personales.personal'),
        ),
        migrations.AlterField(
            model_name='salidaproducto',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salidaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
